version: '3'

services:
  app:
    build: .
    volumes:
      - .:/go/src/

  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=godatabase
      - MYSQL_ROOT_PASSWORD=root

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9094:9094
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPICS_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INERNAL://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISID_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://host.docker.internal:172.17.0.1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
    extra_hosts:
      - "host.docker.internal:172.17.0.1"